sudo: required

language: cpp

services: docker

install:
   - docker build -t base:travis -f docker/Dockerfile.travis docker/

script:
   - echo "`pwd`"
   - docker run --rm -v `pwd`:/opt/sources/base arwmar/images:base "cd /opt/sources/base && mkdir build && cd build && cmake ../ && make"
