sudo: false

language: cpp
compiler: gcc

addons:
   apt:
      packages:
      - libboost-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-test-dev
      - cmake

before_script:
   - mkdir build

script:
   - cd build
   - cmake ../
   - make

