sudo: required

services: docker

language: python

install:
   - docker pull arwmar/base:travis

script:
   - docker run --rm -v `pwd`:/opt/sources/base arwmar/base:travis
      /bin/bash -c "cd /opt/sources/base && mkdir build && cd build && cmake ../ && make"
